### PR TITLE
Remove JNA 4.1.* and 5.* (all versions except 4.5.1)

### PR DESCRIPTION
**Pull request by jonahgraham**
For now JNA 4.5.1 is kept because it is needed by httpclient4
which is still used by many consumers (ECF, Mylyn, User Storage)

Eclipse Platform is already using 5.13 which is newer than
latest in Orbit

Part of #25

### CODE REVIEW

**Comment by jonahgraham** [comment]
oshi depends on this, so #33 needs to go first.

**Comment by jonahgraham** [comment]
To be able to merge this we need to get rid of (at least) org.apache.httpcomponents.httpclient.win 4.5.14.v20230629-2340 as it depends on JNA < 5.0, but maven-simrel only has >= 5 in it.

**Comment by jonahgraham** [comment]
> To be able to merge this we need to get rid of (at least) org.apache.httpcomponents.httpclient.win 4.5.14.v20230629-2340 as it depends on JNA < 5.0, but maven-simrel only has >= 5 in it.

I updated the PR to not remove the 4.5 version of JNA as the dependencies are wide ranging still.

**Comment by merks** [comment]
I noticed that the latest version of SimRel aggregation has no older com.sun.jna bundle version than version 5.13.0.   The org.apache.httpcomponents.httpclient.win  fragment is also not present.  Maybe this was overlooked?

https://repo1.maven.org/maven2/org/apache/httpcomponents/httpclient-win/4.5.14/

**Comment by jonahgraham** [comment]
SimRel doesn't - but to get rid of 4.5 I needed to get rid of httpclient.win from Orbit itself otherwise orbit stopped building.

With your exclusion approach it is much better anyway.

**Comment by merks** [comment]
Yes, I think we could go down the exclusion path for quite some time before we need to or should take action in the Git repository itself.   I'm up to 136 excluded bundles with 169 included bundles remaining.  A bunch don't even appear to be used in SimRel...

**Pull request merged**
