### PR TITLE
Import javax.annotation with more restrictive version range

### PR DESCRIPTION
**Pull request by guw**
Required for proper resolution when jsr305 is present in same target platform.

Fixes https://github.com/eclipse-platform/eclipse.platform.ui/issues/727
https://github.com/eclipse-platform/eclipse.platform.ui/pull/738

### CODE REVIEW

**Comment by guw** [comment]
@jonahgraham Is Orbit officially on GitHub now? Is it ok to merge the PR and publish a new version?

**Comment by merks** [comment]
Yes, it's on GitHub. I'm not so familiar with the details but I assume it will modify what's current generated to specify upper bounds on these 3 requirements:

image

**Comment by guw** [comment]
> I assume it will modify what's current generated to specify upper bounds on these 3 requirements

Correct. This will prevent importing (and re-exporting) the bogus JSR 305 version of the packages.

**Comment by merks** [comment]
Yes, that seems good!

**Pull request merged**
