### PR TITLE
Upgrade JaCoCo to 0.8.10

### PR DESCRIPTION
**Pull request by Godin**

### CODE REVIEW

**Review by jonahgraham — APPROVED** [review]

**Comment by jonahgraham** [comment]
@Godin Where are we with this?

**Comment by Godin** [comment]
@jonahgraham I had a quick call with @marchof a few days ago - he agree that there is not much value in postponing the move away from Orbit if it can be done now.

BTW @marchof jar-signing of JaCoCo during its releases won't help the users of old Eclipse versions, because sooner or later newer ASM version will be required and ASM is not jar-signed in Maven Central 😉 

So I was testing the use of https://download.eclipse.org/oomph/simrel-maven/2023-06 provided by @merks  and the changes required for it in EclEmma  - mainly an upgrade of Tycho to `2.7.5` and corresponding tweaks for https://ci.eclipse.org/eclemma/

With these changes update of EclEmma in the Eclipse versions

* up to `4.19 (2021-03)` causes the following warning as expected


* in the versions from `4.23 (2022-03)` up to the latest released `4.27 (2023-03)` everything is just fine 🎉 

* however in the versions from `4.20 (2021-06)` to `4.22 (2021-12)` I got the following


with the following errors in Error Log

```
eclipse.buildId=4.20.0.I20210611-1600
java.version=16.0.1
java.vendor=Oracle Corporation
BootLoader constants: OS=macosx, ARCH=x86_64, WS=cocoa, NL=en_GB
Framework arguments:  -product org.eclipse.epp.package.java.product -keyring /Users/godin/.eclipse_keyring
Command-line arguments:  -os macosx -ws cocoa -arch x86_64 -product org.eclipse.epp.package.java.product -keyring /Users/godin/.eclipse_keyring

org.eclipse.equinox.p2.artifact.repository
Error
Fri May 05 15:06:15 CEST 2023
org.bouncycastle.openpgp.PGPPublicKey found where PGPPublicKeyRing expected

org.bouncycastle.openpgp.PGPException: org.bouncycastle.openpgp.PGPPublicKey found where PGPPublicKeyRing expected
	at org.bouncycastle.openpgp.PGPPublicKeyRingCollection.<init>(Unknown Source)
	at org.bouncycastle.openpgp.jcajce.JcaPGPPublicKeyRingCollection.<init>(Unknown Source)
	at org.eclipse.equinox.internal.p2.artifact.processors.pgp.PGPSignatureVerifier.readPublicKeys(PGPSignatureVerifier.java:134)
	at org.eclipse.equinox.internal.p2.artifact.processors.pgp.PGPSignatureVerifier.readPublicKeys(PGPSignatureVerifier.java:150)
	at org.eclipse.equinox.internal.p2.artifact.processors.pgp.PGPSignatureVerifier.initialize(PGPSignatureVerifier.java:90)
	at org.eclipse.equinox.internal.p2.artifact.repository.simple.SimpleArtifactRepository.addPGPSignatureVerifier(SimpleArtifactRepository.java:494)
	at org.eclipse.equinox.internal.p2.artifact.repository.simple.SimpleArtifactRepository.addPostSteps(SimpleArtifactRepository.java:481)
	at org.eclipse.equinox.internal.p2.artifact.repository.simple.SimpleArtifactRepository.processDestination(SimpleArtifactRepository.java:1142)
	at org.eclipse.equinox.internal.p2.artifact.repository.simple.SimpleArtifactRepository.getArtifact(SimpleArtifactRepository.java:782)
	at org.eclipse.equinox.internal.p2.artifact.repository.MirrorRequest.getArtifact(MirrorRequest.java:319)
	at org.eclipse.equinox.internal.p2.artifact.repository.MirrorRequest.transferSingle(MirrorRequest.java:289)
	at org.eclipse.equinox.internal.p2.artifact.repository.MirrorRequest.transfer(MirrorRequest.java:225)
	at org.eclipse.equinox.internal.p2.artifact.repository.MirrorRequest.perform(MirrorRequest.java:155)
	at org.eclipse.equinox.internal.p2.artifact.repository.simple.SimpleArtifactRepository.getArtifact(SimpleArtifactRepository.java:770)
	at org.eclipse.equinox.internal.p2.artifact.repository.simple.DownloadJob.run(DownloadJob.java:64)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
```

Is it a known problem with these versions? According to https://github.com/eclipse/xtext/issues/2133#issuecomment-1379919809 by @merks 

> at least the 2022-03 release before which the PGP support was broken

seems so, but wanna double-check in case this is something fixable on our side. Even if not, then anyway ok, at least we are aware and will be recommending to the users update their Eclipse.

All in all, I plan to substitute this PR with the removal of JaCoCo from Orbit and finish with changes in EclEmma soon/before Orbit M3.

**Comment by merks** [comment]
Unfortunately the initial version of PGP support that was released only looked for the key on the repository's properties not on the artifact's properties and then none of the infrastructure, such as mirroring or downloading and artifact into a pool, preserved the key.  As such, the key was often missing.   So no, unfortunately this is not fixable at your end for those versions.  😢

**Comment by Godin** [comment]
Superseded by https://github.com/eclipse/orbit/pull/18

**Pull request closed without merging**
